package com.shonny.backend.utils;

import java.util.HashSet;
import java.util.Set;

public class EmailUtils {
	private static final Set<String> blacklistEmail = generateBlacklist(); 

	public static boolean emailValid(String email) {
		if (email == null || email.split("@").length != 2) {
			return false;
		}
		String emailServer = email.split("@")[1];
		return !blacklistEmail.contains("@" + emailServer);
	}
	
	private static Set<String> generateBlacklist() {
		Set<String> blacklistEmail = new HashSet<String>();
		blacklistEmail.add("@tempr.email") ;
		blacklistEmail.add("@discard.email") ;
		blacklistEmail.add("@discardmail.com") ;
		blacklistEmail.add("@discardmail.de");
		blacklistEmail.add("@spambog.com") ;
		blacklistEmail.add("@spambog.de");
		blacklistEmail.add("@spambog.ru") ;
		blacklistEmail.add("@0815.ru") ;
		blacklistEmail.add("@btcmail.pw");
		blacklistEmail.add("@knol-power.nl") ;
		blacklistEmail.add("@hartbot.de") ;
		blacklistEmail.add("@freundin.ru") ;
		blacklistEmail.add("@smashmail.de");
		blacklistEmail.add("@s0ny.net");
		blacklistEmail.add("@pecinan.net");
		blacklistEmail.add("@budaya-tionghoa.com");
		blacklistEmail.add("@lajoska.pe.hu") ;
		blacklistEmail.add("@1mail.x24hr.com") ;
		blacklistEmail.add("@from.onmypc.info");
		blacklistEmail.add("@now.mefound.com") ;
		blacklistEmail.add("@mowgli.jungleheart.com");
		blacklistEmail.add("@myfreemail.space");
		blacklistEmail.add("@gabox.store");
		blacklistEmail.add("@yourspamgoesto.space");
		blacklistEmail.add("@pecinan.org");
		blacklistEmail.add("@budayationghoa.com");
		blacklistEmail.add("@katergizmo.de") ;
		blacklistEmail.add("@CR.cloudns.asia");
		blacklistEmail.add("@TLS.cloudns.asia");
		blacklistEmail.add("@MSFT.cloudns.asia");
		blacklistEmail.add("@B.cr.cloUdnS.asia") ;
		blacklistEmail.add("@ssl.tls.cloudns.ASIA") ;
		blacklistEmail.add("@sweetxxx.de");
		blacklistEmail.add("@DVD.dns-cloud.net") ;
		blacklistEmail.add("@DVD.dnsabr.com");
		blacklistEmail.add("@BD.dns-cloud.net") ;
		blacklistEmail.add("@YX.dns-cloud.net");
		blacklistEmail.add("@SHIT.dns-cloud.net");
		blacklistEmail.add("@SHIT.dnsabr.com");
		blacklistEmail.add("@eu.dns-cloud.net");
		blacklistEmail.add("@eu.dnsabr.com");
		blacklistEmail.add("@asia.dnsabr.com") ;
		blacklistEmail.add("@8.dnsabr.com") ;
		blacklistEmail.add("@pw.8.dnsabr.com");
		blacklistEmail.add("@mm.8.dnsabr.com");
		blacklistEmail.add("@23.8.dnsabr.com") ;
		blacklistEmail.add("@email-mail.pw");
		blacklistEmail.add("@pw.Email-Mail.cf");
		blacklistEmail.add("@ETR500.ga");
		blacklistEmail.add("@ETR500.gq");
		blacklistEmail.add("@x.dc74.ml");
		blacklistEmail.add("@x.dc74.cf");
		blacklistEmail.add("@mailpost.gq") ;
		blacklistEmail.add("@pecinan.com") ;
		blacklistEmail.add("@disposable-email.ml") ;
		blacklistEmail.add("@pw.epac.to") ;
		blacklistEmail.add("@brunhilde.ml") ;
		blacklistEmail.add("@MAILPOST.ga");
		blacklistEmail.add("@giallo.tk");
		blacklistEmail.add("@giallo.cf");
		blacklistEmail.add("@giallo.ml");
		blacklistEmail.add("@giallo.gq");
		blacklistEmail.add("@cologno.cf");
		blacklistEmail.add("@postheo.de");
		blacklistEmail.add("@my.viola.gq") ;
		blacklistEmail.add("@spam.viola.gq");
		blacklistEmail.add("@tempr.email.viola.gq");
		blacklistEmail.add("@Email.Viola.Gq") ;
		blacklistEmail.add("@grey.grigio.cf");
		blacklistEmail.add("@gray.grigio.cf");
		blacklistEmail.add("@bianco.cf");
		blacklistEmail.add("@bianco.ml");
		blacklistEmail.add("@bianco.ga");
		blacklistEmail.add("@white.bianco.cf");
		blacklistEmail.add("@white.bianco.ml");
		blacklistEmail.add("@white.bianco.ga");
		blacklistEmail.add("@sexy.camdvr.org");
		blacklistEmail.add("@gay.theworkpc.com") ;
		blacklistEmail.add("@XMPR.tk") ;
		blacklistEmail.add("@XMPR.cf") ;
		blacklistEmail.add("@ETR610.cf");
		blacklistEmail.add("@ETR610.ga");
		blacklistEmail.add("@ETR610.gq") ;
		blacklistEmail.add("@black.bianco.cf") ;
		blacklistEmail.add("@Purple.viola.gq") ;
		blacklistEmail.add("@Disposable.ml") ;
		blacklistEmail.add("@Conwex.cf");
		blacklistEmail.add("@Disposable-e.ml");
		blacklistEmail.add("@09stees.online") ;
		blacklistEmail.add("@07stees.online") ;
		blacklistEmail.add("@careerwill.com") ;
		blacklistEmail.add("@barnyarthartakar.com") ;
		blacklistEmail.add("@googulliver.site");
		blacklistEmail.add("@gullivervip.space");
		blacklistEmail.add("@nonciclopedia.tk");
		blacklistEmail.add("@nonciclopedia.cf") ;
		blacklistEmail.add("@nonciclopedia.ml");
		blacklistEmail.add("@nonciclopedia.ga");
		blacklistEmail.add("@nonciclopedia.gq");
		blacklistEmail.add("@firema.tk") ;
		blacklistEmail.add("@firema.cf") ;
		blacklistEmail.add("@firema.ml") ;
		blacklistEmail.add("@firema.ga");
		blacklistEmail.add("@firema.gq");
		blacklistEmail.add("@1000.frecciarossa.tk");
		blacklistEmail.add("@&nbsp");;
		blacklistEmail.add("@jancok.in");
		blacklistEmail.add("@bangsat.in");
		blacklistEmail.add("@kontol.co.uk");
		blacklistEmail.add("@kontol.city");
		blacklistEmail.add("@barrabravaz.com");
		blacklistEmail.add("@opende.de");
		blacklistEmail.add("@v250.tk");
		blacklistEmail.add("@ETR500.cf");
		blacklistEmail.add("@monachat.tk");
		blacklistEmail.add("@2.MMspa.cf");
		blacklistEmail.add("@Marrone.CF");
		blacklistEmail.add("@x.Marrone.cf") ;
		blacklistEmail.add("@GM.marrone.cf") ;
		blacklistEmail.add("@sex.marrone.cf");
		blacklistEmail.add("@azzurro.cf");
		blacklistEmail.add("@azzurro.ga");
		blacklistEmail.add("@azzurro.gq");
		blacklistEmail.add("@Brown.Marrone.Cf") ;
		blacklistEmail.add("@Pw.Brown.Marrone.Cf");
		blacklistEmail.add("@Conwex.ml");
		blacklistEmail.add("@Conwex.tk");
		blacklistEmail.add("@Mytrash.tk") ;
		blacklistEmail.add("@Mytrash.cf");
		blacklistEmail.add("@Mytrash.ml") ;
		blacklistEmail.add("@Mytrash.ga") ;
		blacklistEmail.add("@Mytrash.gq");
		blacklistEmail.add("@HitachiRailSTS.cf");
		blacklistEmail.add("@HitachiRailSTS.ml");
		blacklistEmail.add("@Mediaset.gq") ;
		blacklistEmail.add("@Mediaset.cf") ;
		blacklistEmail.add("@laokzmaqz.tech");
		blacklistEmail.add("@gullivervip.site");
		blacklistEmail.add("@yopmail.com");
		blacklistEmail.add("@maildrop.cc");
		blacklistEmail.add("@mailinator.com");
		blacklistEmail.add("@urhen.com");
		blacklistEmail.add("@spamgourmet.com");
		blacklistEmail.add("@boun.cr");
		blacklistEmail.add("@getnada.com");
		blacklistEmail.add("@guerrillamail.info");
		blacklistEmail.add("@grr.la");
		blacklistEmail.add("@guerrillamail.biz");
		blacklistEmail.add("@guerrillamail.com");
		blacklistEmail.add("@guerrillamail.de");
		blacklistEmail.add("@guerrillamail.net");
		blacklistEmail.add("@guerrillamail.org");
		blacklistEmail.add("@guerrillamailblock.com");
		blacklistEmail.add("@pokemail.net");
		blacklistEmail.add("@spam4.me");
		blacklistEmail.add("@dispostable.com") ;
		blacklistEmail.add("@dmail1.net");
		blacklistEmail.add("@harakirimail.com");
		blacklistEmail.add("@*.33mail.com");
		blacklistEmail.add("@inboxkitten.com");
		blacklistEmail.add("@altmails.com");
		blacklistEmail.add("@fakemyinbox.com");
		blacklistEmail.add("@tryninja.io");
		blacklistEmail.add("@burnermail.io");
		blacklistEmail.add("@ppetw.com");
		blacklistEmail.add("@uacro.com");
		blacklistEmail.add("@pmlep.de");
		blacklistEmail.add("@zhcne.com");
		blacklistEmail.add("@fls4.gleeze.com");
		blacklistEmail.add("@barryogorman.com");
		blacklistEmail.add("@isdaq.com");
		blacklistEmail.add("@mailed.ro");
		blacklistEmail.add("@dfg6.kozow.com");
		blacklistEmail.add("@mailfs.com");
		blacklistEmail.add("@xww.ro");
		blacklistEmail.add("@ppetw.com");
		blacklistEmail.add("@i.xcode.ro");
		blacklistEmail.add("@o.opendns.ro");
		blacklistEmail.add("@glubex.com");
		blacklistEmail.add("@m07.ovh");
		blacklistEmail.add("@iiron.us");
		blacklistEmail.add("@mailsucker.net");
		blacklistEmail.add("@sobhog.com");
		blacklistEmail.add("@receivednow.com");
		blacklistEmail.add("@erine.email");
		blacklistEmail.add("@0box.eu");
		blacklistEmail.add("@contbay.com");
		blacklistEmail.add("@damnthespam.com");
		blacklistEmail.add("@kurzepost.de");
		blacklistEmail.add("@objectmail.com");
		blacklistEmail.add("@proxymail.eu");
		blacklistEmail.add("@rcpt.at");
		blacklistEmail.add("@trash-mail.at");
		blacklistEmail.add("@trashmail.at");
		blacklistEmail.add("@trashmail.com");
		blacklistEmail.add("@trashmail.io");
		blacklistEmail.add("@trashmail.me");
		blacklistEmail.add("@trashmail.net");
		blacklistEmail.add("@wegwerfmail.de");
		blacklistEmail.add("@wegwerfmail.net");
		blacklistEmail.add("@wegwerfmail.org");
		blacklistEmail.add("@moakt.cc");
		blacklistEmail.add("@disbox.net");
		blacklistEmail.add("@tmpmail.org");
		blacklistEmail.add("@tmpmail.net");
		blacklistEmail.add("@tmails.net");
		blacklistEmail.add("@disbox.org");
		blacklistEmail.add("@moakt.co");
		blacklistEmail.add("@moakt.ws");
		blacklistEmail.add("@tmail.ws");
		blacklistEmail.add("@bareed.ws");
		blacklistEmail.add("@zerodog.icu");
		blacklistEmail.add("@emohawk.xyz");
		blacklistEmail.add("@mrflibble.icu");
		blacklistEmail.add("@psirens.icu");
		blacklistEmail.add("@cdcovers.icu");
		blacklistEmail.add("@xsellize.xyz");
		blacklistEmail.add("@imgrpost.xyz");
		blacklistEmail.add("@jamesmaylovescabbage.xyz");
		blacklistEmail.add("@app1e.xyz");
		blacklistEmail.add("@polymorph.icu");
		blacklistEmail.add("@camille.pw");
		blacklistEmail.add("@epideme.xyz");
		blacklistEmail.add("@mailsac.com");
		blacklistEmail.add("@20mail.it");
		blacklistEmail.add("@26fuli.com");
		blacklistEmail.add("@blackgarlictea.site");
		blacklistEmail.add("@myakapulko.ga");
		blacklistEmail.add("@aletar.ga");
		blacklistEmail.add("@lilittka.cf");
		blacklistEmail.add("@pukimay.gq");
		blacklistEmail.add("@hiyaa.site");
		blacklistEmail.add("@thegigabithk.com");
		blacklistEmail.add("@volknakone.cf");
		blacklistEmail.add("@oceansidenailsalons.com");
		blacklistEmail.add("@astoryending.com");
		blacklistEmail.add("@storm-gain.net");
		blacklistEmail.add("@innovateccc.org");
		blacklistEmail.add("@payperdonation.org");
		blacklistEmail.add("@theglockner.com");
		blacklistEmail.add("@ososos.ml");
		blacklistEmail.add("@bacninhmail.us");
		return blacklistEmail;
	}
}
